### ISSUE TITLE
Go get does not get versions after v6.0.14

### ISSUE THREAD

**Issue by heppu** [minio/minio-go#1107]
I'm using minio-go v6.0.13 and I need to update to v6.0.24 but `go get -u github.com/minio/minio-go` only updates to v6.0.14.

If I create new project  `go mod init my-project` with following main.go:

```go
package main

import _ "github.com/minio/minio-go"

func main() {}
```

and then run `go get`, I end up with following go.mod file:

```go
module my-project

go 1.12

require (
	github.com/go-ini/ini v1.42.0 // indirect
	github.com/minio/minio-go v6.0.14+incompatible
	github.com/mitchellh/go-homedir v1.1.0 // indirect
	golang.org/x/crypto v0.0.0-20190513172903-22d7a77e9e5f // indirect
	golang.org/x/net v0.0.0-20190520210107-018c4d40a106 // indirect
)
```

I have not encountered this with other libraries so why go get is not fetching latest minio-go version?

**Comment by harshavardhana** [comment]
All you have to do is `go get github.com/minio/minio-go@master`  never use `-u` with go mod

**Comment by kannappanr** [comment]
@heppu closing this as answered. Please feel free to reach out to us on slack at https://slack.min.io for such questions.

**Comment by heppu** [comment]
> All you have to do is `go get github.com/minio/minio-go@master` never use `-u` with go mod

I don't want fetch master, I want to fetch latest release. And what you said about never using -u, that is the way how you should update your dependencies and it is described in multiple places in go modules docs. [https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies](https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies)

**Comment by harshavardhana** [comment]
Yes but -u is meant to update all dependencies recursively, that is not a good idea in general because that may make your current dep incompatible.  Our latest release is latest master we make releases every week. So you can be sure that sticking to a commit will work fine.

There is another issue that we will address related to `go mod` behavior which will be addressed in a separate issue.

**Comment by harshavardhana** [comment]
Yes but -u is meant to update all dependencies recursively, that is not a good idea in general because that may make your current dep incompatible.  Our latest release is latest master we make releases every week. So you can be sure that sticking to a commit will work fine.

There is another issue that we will address related to `go mod` behavior which will be addressed in a separate issue.
