### ISSUE TITLE
Bucket name appending when uploading file to s3

### ISSUE THREAD

**Issue by knrt10** [minio/minio-go#1123]
When I am trying to upload a file to s3, I already have a bucket but when I try uploading a file to that bucketname like this

`FPutObject(bucketname, key, filePath, minio.PutObjectOptions{ContentType: contentType})`

then I have file inside my s3 like `bucketname/bucketname/key`. I don't want this to happen. I just want my file to be inside `bucketname/key`. Is it the default behaviour of minio client or I am doing anything wrong. Please help

**Comment by nitisht** [comment]
@knrt10 I tried this locally and can't reproduce the problem. Do you have the `key` in format `bucketname/key`?

**Comment by knrt10** [comment]
I am sorry but I my key did not contain bucketname

**Comment by kannappanr** [comment]
@knrt10 I tried reproducing the issue here just like @nitisht and was unable to reproduce the issue. Can you give a sample code that you are testing with, I tried the one in https://github.com/minio/minio-go/blob/master/examples/s3/fputobject.go

Also, are you connecting to `AWS-S3` or any other `S3` server? 

You can redact the `access` and `secret` keys and post your code.

**Comment by knrt10** [comment]
I am using old version of minio-client, I think using latest might solve my problem. Thanks a lot for your help

**Comment by kannappanr** [comment]
Can I know which version of minio-go you were using? I don't think we should any of these issues.
