### ISSUE TITLE
Expose server properties

### ISSUE THREAD

**Issue by lukepighetti** [minio/minio-go#1134]
`mineo-js` exposes the protocol, host, and port, which makes it easy to build your own public URLs. This doesn't work on golang because the server properties are not exposed to `Minio.Client`

https://github.com/minio/minio-js/issues/588#issuecomment-318968856

```
var publicUrl = minioClient.protocol + '//' + minioClient.host + ':' + minioClient.port + '/' + minioBucket + '/' + obj.name
```

**Comment by harshavardhana** [comment]
Server properties are provided by you as input while initializing the client object, doesn't that work ? . Constructing a url.URL is pretty simple.

**Comment by lukepighetti** [comment]
It is a manner of convenience. In the JS client this URL is also located on the Client object. It is convenient and would work well in `minio-go` as well, requesting reversal of `wontfix`.

**Comment by harshavardhana** [comment]
Let us think about it @lukepighetti

**Comment by aead** [comment]
I'm not really sure I understand the request here.
So in go code you have something like:
```
const (
         s3Protocol = "https"
         s3Endpoint = "localhost"
         s3EndpointPort = "9000"
        // ...     
)
url := fmt.Sprintf("%s://%s:%s", s3Protocol, s3Endpoint, s3EndpointPort) // for example
```
(Similarly via CLI arguments or env. vars.)

I'm not really sure what the purpose of the proposed config struct is?!
We can add a `EndpointURL()` method to the `S3Client` such that the URL is accessible whenever you pass / use the client struct - even though I don't see why this should useful in particular.

**Comment by aead** [comment]
I'm not really sure I understand the request here.
So in go code you have something like:
```
const (
         s3Protocol = "https"
         s3Endpoint = "localhost"
         s3EndpointPort = "9000"
        // ...     
)
url := fmt.Sprintf("%s://%s:%s", s3Protocol, s3Endpoint, s3EndpointPort) // for example
```
(Similarly via CLI arguments or env. vars.)

I'm not really sure what the purpose of the proposed config struct is?!
We can add a `EndpointURL()` method to the `S3Client` such that the URL is accessible whenever you pass / use the client struct - even though I don't see why this is useful in particular.

**Comment by lukepighetti** [comment]
The way it works today

```
minio.New("localhost:9000",
	"AKIAIOSFODNN7EXAMPLE", "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
	false)
```

With an options struct

```
minio.New(minio.Options{
	SSL:       true,
	Host:      "localhost:9000",
	AccessID:  "AKIAIOSFODNN7EXAMPLE",
	SecretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
})
```

That all said, it would be nice to not have `secure` bool, but to instead do this


```
client, err := minio.New(minio.Options{
	Host:      "https://localhost:9000",
	AccessID:  "AKIAIOSFODNN7EXAMPLE",
	SecretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
})
```

from there you could grab the host like so

```
host := client.Options.Host
```

**Comment by aead** [comment]
I agree in general that having just a URL - like `https://localhost:9000` instead of 3 (4) separate parameters is probably more convenient. In particular, the `secure` / `TLS` flag is probably a not really ergonomic.

However, `host := client.Options.Host` is probably not the right thing to do. For example what should happen if someone performs `client.Options.Host = "https://some-domain.com:9000"`? Should that change affect the internal configuration of the client? If yes, what happens for an invalid host - panic/error later on? If no, then any execution of `host := client.Options.Host` later in time returns an incorrect value... Both behaviors can cause subtle bugs that are hard to identify...

I suspect that unifying the endpoint parts into one URL "just" because of being more convenient does not justify a major breaking change, right @harshavardhana ?! However, I agree that at least having one `New` function taking just the URL and not the URL parts would have been a better API design in the first place @lukepighetti 

Therefore, I would consider a 
 - `func EndpointURL() url.URL`
 - or  `func Endpoint() string`
-  or `func Host() string`

as the favorable solution given the current API...

**Comment by harshavardhana** [comment]
> * `func EndpointURL() url.URL`

This is perhaps what I was thinking we can do @aead `func (c *Client) EndpointURL() url.URL`

**Comment by lukepighetti** [comment]
`func EndpointURL() url.Url` makes sense to me and it fortunately means no breaking changes
