### ISSUE TITLE
PutObjectWithContext() gets stuck if reading an empty file from a progress bar io.Reader

### ISSUE THREAD

**Issue by falzm** [minio/minio-go#1146]
Hi,

We're facing an [issue in the Exoscale CLI](https://github.com/exoscale/cli/issues/138) where objects uploads get stuck at reading if files are empty. At first it looked like an issue in the progress bar we use, but after some practical tests its author [is suggesting the issue might be located](https://github.com/vbauerster/mpb/issues/7#issuecomment-518756758) in your library. Could you please have a look at this problem? Let me know if you need me to run additional tests.

Version used: v6.0.29

**Comment by harshavardhana** [comment]
So I used progress bar from chegaa/pb

```go
package main

import (
	"bytes"
	"context"
	"log"

	"github.com/cheggaaa/pb/v3"
	"github.com/minio/minio-go/v6"
)

func main() {
	// Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY, my-testfile, my-bucketname and
	// my-objectname are dummy values, please replace them with original values.

	// Requests are always secure (HTTPS) by default. Set secure=false to enable insecure (HTTP) access.
	// This boolean value is the last argument for New().

	// New returns an Amazon S3 compatible client object. API compatibility (v2 or v4) is automatically
	// determined based on the Endpoint value.
	s3Client, err := minio.New("play.min.io", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", true)
	if err != nil {
		log.Fatalln(err)
	}

	// Progress reader is notified as PutObject makes progress with
	// the Reads inside.
	progress := pb.New64(0)
	progress.Start()
	emptyReader := bytes.NewReader([]byte(""))
	n, err := s3Client.PutObjectWithContext(context.Background(), "testbucket", "my-objectname-progress", emptyReader, emptyReader.Size(), minio.PutObjectOptions{ContentType: "application/octet-stream", Progress: progress.NewProxyReader(emptyReader)})

	if err != nil {
		log.Fatalln(err)
	}
	progress.Finish()
	log.Println("Uploaded", "my-objectname", " of size: ", n, "Successfully.")
}
```

**Comment by harshavardhana** [comment]
So I debugged the code to figure out why this is happening. Because we explicitly set req.Body as nil, without any non-nil body - this is an upstream Go bug and has been there historically https://github.com/aws/aws-sdk-go/commit/db7b69949079da41d74f9c6bfb150becb48db1e1 

```
 ---------START-HTTP---------
PUT /testbucket/my-objectname-progress HTTP/1.1
Host: play.min.io
User-Agent: MinIO (linux; amd64) minio-go/v6.0.34
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190806/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20190806T234850Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Length: 0
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Date: Tue, 06 Aug 2019 23:48:50 GMT
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 15B87A4A617506C5
X-Amz-Server-Side-Encryption: AES256
X-Xss-Protection: 1; mode=block
---------END-HTTP---------
```

The object is indeed uploaded since the progress didn't move the progress bar is stuck. 

```go
package main

import (
	"bytes"
	"context"
	"log"
	"os"
	"time"

	"github.com/minio/minio-go"
	"github.com/vbauerster/mpb"
	"github.com/vbauerster/mpb/decor"
)

func main() {
	// Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY, my-testfile, my-bucketname and
	// my-objectname are dummy values, please replace them with original values.

	// Requests are always secure (HTTPS) by default. Set secure=false to enable insecure (HTTP) access.
	// This boolean value is the last argument for New().

	// New returns an Amazon S3 compatible client object. API compatibility (v2 or v4) is automatically
	// determined based on the Endpoint value.
	s3Client, err := minio.New("play.min.io", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", true)
	if err != nil {
		log.Fatalln(err)
	}

	s3Client.TraceOn(os.Stderr)

	p := mpb.New(
		mpb.WithWidth(60),
		mpb.WithRefreshRate(180*time.Millisecond),
	)

	bar := p.AddBar(0, mpb.BarStyle("[=>-|"),
		mpb.PrependDecorators(
			decor.CountersKibiByte("% .2f / % .2f"),
		),
		mpb.AppendDecorators(
			decor.EwmaETA(decor.ET_STYLE_GO, float64(0)/2048),
			decor.Name(" ] "),
			decor.AverageSpeed(decor.UnitKiB, "% .2f"),
		),
	)

	emptyReader := bytes.NewReader([]byte(""))
	proxyReader := bar.ProxyReader(emptyReader)
	defer proxyReader.Close()

	n, err := s3Client.PutObjectWithContext(context.Background(), "testbucket",
		"my-objectname-progress", emptyReader, emptyReader.Size(),
		minio.PutObjectOptions{
			ContentType: "application/octet-stream",
			Progress:    proxyReader,
		})

	if err != nil {
		log.Fatalln(err)
	}
	p.Wait()
	log.Println("Uploaded", "my-objectname", " of size: ", n, "Successfully.")
}
```

While the object is indeed uploaded since the underlying reader is not reading the progress, the progress reader doesn't see an EOF which leads to a situation where it hangs. But since its a 0-byte file there is no progress bar, to begin with.

Go net/http client is pretty weird about how it handles empty body. So fixing this issue perhaps is going to be a problem, it will expose us again to other workarounds that we had to add to circumvent issues with zero bytes.

**Comment by harshavardhana** [comment]
Another notorious example is perhaps this 

https://golang.org/src/net/http/request.go?h=outgoingLength#L1368

```
// outgoingLength reports the Content-Length of this outgoing (Client) request.
// It maps 0 into -1 (unknown) when the Body is non-nil.
func (r *Request) outgoingLength() int64 {
	if r.Body == nil || r.Body == NoBody {
		return 0
	}
	if r.ContentLength != 0 {
		return r.ContentLength
	}
	return -1
}
```

So regardless of what you might have set to req.ContentLength it is auto probed internally and makes it really hard.  Because either the body has to be nil or equals http.NoBody - any wrapping by the caller makes it really hard to handle this. 

Meaning if you didn't set this value and req.ContentLength is still set to '0' then the outgoingLength() will auto return "-1" which will fail for calls to AWS S3 since it explicitly requires Content-Length to be set. 

At this point, I think the effort required to support this doesn't justify the effort needed on our end as we are as short-handed as you are.

NOTE: This is the same issue with aws-sdk-go as well.

**Comment by falzm** [comment]
@harshavardhana well thank you for the tests, I'll add the workaround suggested by @vbauerster in https://github.com/vbauerster/mpb/issues/7#issuecomment-518756758

**Comment by harshavardhana** [comment]
I will perhaps try to persuade upstream to handle this properly in net/http perhaps in go1.13 cycle, because clearly they don't honor what was set by the caller here.

Thanks for using a workaround here @falzm

**Comment by kannappanr** [comment]
@falzm Closing the issue now. Please feel free to reach out to us if you have further questions.
