### ISSUE TITLE
Memleak-ish behavior of PutObjectWithContext

### ISSUE THREAD

**Issue by janekolszak** [minio/minio-go#1176]
Hi,
I'm uploading a lot of data from a machine that has just couple of Gs of RAM.
When I call `PutObjectWithContext` GO program gets killed by OOM.

I made some experiments end it turns out that if I configure the GC to run more often it seems to work, but it isn't a real solution.

It seems that minio has somewhere a buffer that gets allocated on every read and waits for the GC to be freed. Maybe you could just use one buffer and reuse it?

**Comment by harshavardhana** [comment]
Please share a full program to show the issue..

**Comment by janekolszak** [comment]
So it's something like this. The problem occurs when `writeABigFile` is called. Minio gets about 14G of data to send and the machine has about 1G of RAM. When I replace minio with the commented loop it works.

```
	wait := sync.WaitGroup{}
	wait.Add(1)

	pipeReader, pipeWriter := io.Pipe()
	var errWrite error
	go func() {
		defer wait.Done()
		defer pipeWriter.Close()

		zipWriter := zip.NewWriter(pipeWriter)

		errWrite = writeABigFile(ctx, db, zipWriter)
		if errWrite != nil {
			return
		}

		errWrite = zipWriter.Close()
		if errWrite != nil {
			return
		}
	}()


	_, err := minioClient.PutObjectWithContext(ctx, bucket, name, pipeReader, -1, minio.PutObjectOptions{ContentType: "application/octet-stream"})
	if err != nil {
		return 
	}

	// If the call to minio is replaced with this there's no problem:
	/*
	buffer := make([]byte, 1024*1024)
	for {
		_, err := pipeReader.Read(buffer)
		if err != nil {
			break
		}
		time.Sleep(time.Second * 5)
	}
	*/
	wait.Wait()

	return errWrite
```

**Comment by klauspost** [comment]
As a quick workaround, does it help if you set 'PartSize' in the options to, say 128MB?

It does seem like the defaults are a bit wonky, which should be fixed.

**Comment by harshavardhana** [comment]
It is not a mem-leak if the input size is "-1" minio-go automatically assumes the maximum possible memory size to fit 5TiB - in S3 API content-length is a must either it's multipart or since PutObject()

This is a minio-go only functionality that allows `-1` with the pretext that the user perhaps wishes to upload a large file even while still keeping the upper bound of 5TiB. In AWS S3 per multipart, there can be at max 10000 parts so minio-go automatically chooses 512MiB per part size. 

This can be definitely reduced by using the PartSize as mentioned by @klauspost so if you did override the auto calculation by specifying a part size - you have to assume that your total upload size automatically reduces based on the part size.

1GiB RAM is generally not a practical scenario of what you are requested @janekolszak minio-go automatically uses 4 go-routines with each 512MiB of RAM - this would easily exceed your arbitrary limit. 

if your use-case is that use minimal RAM avoid passing `-1` instead pick a proper content-length of the stream.

**Comment by klauspost** [comment]
@harshavardhana It still seems like bad behavior and it appears there was an intent to set a default part size so it isn't infinite.

See the PR, which sets a 128MB default part size. I would say that is pretty reasonable behavior.

**Comment by janekolszak** [comment]
I'm not sure the PartSize is the problem. I think that the GO's garbage collector just doesn't free all the buffers in time. I can of course configure GC to run more often (and it works), but it's an overkill - it slows down the app just to fix a bug in minio.

Maybe there should be a callback to run every time a part is sent. 
Or better just reuse one buffer instead of creating new ones?

**Comment by klauspost** [comment]
@janekolszak Have you tried setting the PartSize?

**Comment by klauspost** [comment]
@harshavardhana Close?

**Comment by harshavardhana** [comment]
Closing as per https://github.com/minio/minio-go/issues/1176#issuecomment-546856662

**Comment by tetafro** [comment]
> This can be definitely reduced by using the PartSize as mentioned by @klauspost so if you did override the auto calculation by specifying a part size - you have to assume that your total upload size automatically reduces based on the part size.

@harshavardhana so this workaround with custom `PartSize` should work? I'm getting error with it
```go
t := time.Now().Add(retention)
opts := minio.PutObjectOptions{
    RetainUntilDate: &t,
    ContentType:     "text/csv",
    PartSize:        64 * 1024 * 1024,
}
_, err := client.PutObjectWithContext(ctx, "bucket", "key", reader, -1, opts)
if err {
    log.Fatal(err)
}
```
```
Part size * max_parts(10000) is lesser than input objectSize.
```

**Comment by reverland** [comment]
The workaround don't work anymore. Maybe need a new issue. @tetafro

**Comment by harshavardhana** [comment]
@reverland please provide the right content-length - if you are expecting us to optimally chunk it's not possible and also be memory efficient. 

We shall address the concerns in https://github.com/minio/minio-go/issues/1176#issuecomment-562472216
