### ISSUE TITLE
fix: make more compatible with sub-resource query string 

### ISSUE THREAD

**Issue by JetChars** [minio/minio-go#1230]
- for those aws s3 api like **POST delete multiple objects** should be called like `POST /?delete`, instead of `POST /?delete=` which might cause a compatible issue

- current logic simply concatenates k,v with `=`, without coping with those sub-resources like `delete`, `policy`, `location`, etc...
    - `pkg/s3utils/utils.go`

```go
func QueryEncode(v url.Values) string {
    if v == nil {
        return ""
    }
    var buf bytes.Buffer
    keys := make([]string, 0, len(v))
    for k := range v {
        keys = append(keys, k)
    }
    sort.Strings(keys)
    for _, k := range keys {
        vs := v[k]
        prefix := percentEncodeSlash(EncodePath(k)) + "="
        for _, v := range vs {
            if buf.Len() > 0 {
                buf.WriteByte('&')
            }
            buf.WriteString(prefix)
            buf.WriteString(percentEncodeSlash(EncodePath(v)))
        }
    }
    return buf.String()
}
```

- environment
    - minio-go version(v6.0.48)
    - ceph Hammer(v0.94.5)

**Comment by JetChars** [comment]
I'd like to fix this issue

**Comment by JetChars** [comment]
https://github.com/minio/minio-go/pull/1231/commits/28aff805c2083a272c3542850058ad358f138d46

**Comment by harshavardhana** [comment]
This is not a compatibility issue @JetChars a key with an empty value is same as without `=`

**Comment by harshavardhana** [comment]
in HTTP behavior query param `?localtion=` is same as `?location`  for routing.  This has been around since 5yrs now without any issue with MinIO or AWS S3. 

So whichever vendor you are using is not doing this correctly.

**Comment by JetChars** [comment]
a very old version of ceph(hammer)

**Comment by JetChars** [comment]
![image](https://user-images.githubusercontent.com/5701082/74999014-5f108580-5495-11ea-8d53-5a293db766b2.png)
with the ending `=` will cause 400 at ceph hammer environment

**Comment by harshavardhana** [comment]
Then it's their bug, @JetChars let's not add workarounds for server in client.

**Comment by JetChars** [comment]
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html

according to aws s3 api, there is no end `=`; also, I don't see any drawback remove ending equal sign

**Comment by harshavardhana** [comment]
S3 API doesn't dictate HTTP behavior, it works within the confines.

The problem is making these type of changes which are not warranted because we are messing with Go's net/http's behavior, it will introduce unexpected behavior elsewhere.

In-fact this issue doesn't occur in later versions of Ceph, so it means it's fixed. There is no reason for us to carry this baggage. 

If you wish to still use minio-go you should keep this patch in your fork or upgrade your server.

**Comment by harshavardhana** [comment]
S3 API doesn't dictate HTTP behavior, it works within the confines.

The problem is making these type of changes which are not warranted because we are messing with Go's net/http's behavior, it will introduce unexpected behavior elsewhere.

In-fact this issue doesn't occur in later versions of Ceph, so it means it's fixed. There is no reason for us to carry this baggage. 

If you wish to still use minio-go you should keep this patch in your fork or upgrade your server.

**Comment by JetChars** [comment]
fine, thanks for the reply!
