### ISSUE TITLE
Core.ListObjects and Core.ListObjectsV2 don't allow passing a context

### ISSUE THREAD

**Issue by ItalyPaleAle** [minio/minio-go#1422]
The public methods `Core.ListObjects` and `Core.ListObjectsV2` do not accept a context.Context object as argument. Internally, they just call the private methods `listObjectsQuery` and `listObjectsQueryV2` passing `context.Background()`.

See: https://github.com/minio/minio-go/blob/master/core.go#L46-L56

Because of that, it's not possible to invoke those methods with a custom context that controls the asynchronous tasks.

**Comment by harshavardhana** [comment]
Core APIs are not meant to be used by our users, Core API is for internal use and is not intended to be public-facing. If you are using it - use it at your own risk.

**Comment by ItalyPaleAle** [comment]
If the API was never meant to be used, why exporting it then? (see: https://www.hyrumslaw.com/ )

Anyways, I've run into sitatuons where the Core APIs were the only options for me, so I really hope you don't deprecate them ;)

**Comment by harshavardhana** [comment]
> If the API was never meant to be used, why exporting it then? (see: https://www.hyrumslaw.com/ )

Just because its exported doesn't mean you should willy nilly use it - Core APIs do not have any API guarantees so we may even break them in the future as we see fit.

You should use what is painstakingly documented here https://github.com/minio/minio-go/blob/master/docs/API.md

Unfortunately, Go doesn't have proper provisions to hide APIs from godocs with some form of Java'isk like annotations to guide users, so the best way for you use always use what is written in our API.md
