### ISSUE TITLE
PutObject and size -1 causes massive memory allocation

### ISSUE THREAD

**Issue by J0Nes90** [minio/minio-go#1473]
Gitea is calling PutObject with PutObjectOptions size -1. When doing so with small objects around 30kbs in size the minio sdk allocates around 700MB data whereas everything works fine when providing the actual size directly.

For gitea I've created a docker compose file that uses gitea and minio + some reproduction steps.
https://github.com/go-gitea/gitea/issues/15253

**Comment by harshavardhana** [comment]
You need to control how your parts are going to be uploaded,  unfortunately there is no streaming way to upload in S3 API.

Since the chunking is done automatically inside minio-go when -1 is provided you need to make sure to have a top level partSize limit. Otherwise we will calculate the maximum possible part limit per part to upload 5TiB object maximum object size allowed in AWS S3 upto 10,000 parts.

Either provide the right content length or when using -1 use appropriate PartSize in PutObjectOptions
