### ISSUE TITLE
Upgrading from v7.0.29 to v7.0.32 introduced a go routine leak

### ISSUE THREAD

**Issue by emilhjd** [minio/minio-go#1681]
Did the upgrade, noticed the leak, reverted back to v7.0.29 and the go routine leak was gone.

Will try and identify the leak more precisely, but maybe it is quite clear to someone what happened given that is was recently introduced.

**Comment by harshavardhana** [comment]
This is not enough, you have to tell us exactly what you did and profile your application share the profiles here.

**Comment by harshavardhana** [comment]
Closing @emilhjd please let us know once you have the profiles.

**Comment by alexanderpalsson** [comment]
@harshavardhana we are having a lot of trouble with go routines getting stuck in the [for loop](https://github.com/minio/minio-go/commit/42c18ba23b76627333dbb7f292c50de3eac57c62#diff-282c3c5bf47067eafde30e0ed6f8df086049b4b48891586a3e611b01036f600bL74). Seems like the reqChannel never closes after this change https://github.com/minio/minio-go/commit/42c18ba23b76627333dbb7f292c50de3eac57c62#diff-282c3c5bf47067eafde30e0ed6f8df086049b4b48891586a3e611b01036f600bL78-L85. Since the channel closing with a defer it's never closed since there is nothing triggering the return after the ctx.Done was removed. 

Maybe we are doing something wrong here, but just using the [close](https://github.com/minio/minio-go/blob/master/api-get-object.go#L602-L625) method doesn't seem to close the channel.

**Comment by harshavardhana** [comment]
@alexanderpalsson can you take a look at the PR https://github.com/minio/minio-go/pull/1687 and test it?

**Comment by alexanderpalsson** [comment]
@harshavardhana looks good thank you 😃

**Comment by 260721735** [comment]
![image](https://github.com/minio/minio-go/assets/65893141/a124c805-58cc-4f4a-9e34-9b0c49fe63b0)
I still find problems with v7.0.58
