### ISSUE TITLE
request minio fail

### ISSUE THREAD

**Issue by zadair** [minio/minio-go#1708]
hello，why that? thanks

"message":"Persist: failed to write object: Put \"http://127.0.0.1:19000/testzinc/test_minio_error/1SMmaPbnlaE/000000/000000000017.snp\": readfrom tcp 127.0.0.1:40372->127.0.0.1:19000: http: ContentLength=76 with Body length 0"

**Comment by klauspost** [comment]
Post your code, otherwise we are just guessing.

My guess is that you don't send the data by the reader you are indicating as size.

**Comment by zadair** [comment]
when test zinc, print that err
https://github.com/zinclabs/zinc/blob/main/pkg/bluge/directory/minio.go

in api-put-object-streaming.go +403, reader.size == size is always true，but progressReader.size == size is sometimes false，

so, when pkg/signer/request-signature-streaming.go +288, readfrom baseReadCloser, is incorrect size

**Comment by klauspost** [comment]
@zadair 

1) `size` relies on upstream code. Try using `int64(buf.Len())` instead. 
2) I don't see how your code could ever have worked. [Buffer.Bytes](https://pkg.go.dev/bytes#Buffer.Bytes) should as far as I can tell always return a 0 sized slice, since it returns "the unread portion of the buffer".
3) You should not rely on `Etag == md5(content)` anyway. This is not true in many scenarios.

It could also be a server failing in other ways. Enable [client tracing](https://pkg.go.dev/github.com/minio/minio-go/v7#Client.TraceOn) to see actual response.

**Comment by harshavardhana** [comment]
@zadair please provide us with more precise reproducers otherwise there is nothing actionable on our end.  

Assuming this to be an implementation issue in zinclabs integration. We can re-open when we have more concrete evidence to the contrary.

**Comment by zadair** [comment]
> @zadair please provide us with more precise reproducers otherwise there is nothing actionable on our end.
> 
> Assuming this to be an implementation issue in zinclabs integration. We can re-open when we have more concrete evidence to the contrary.

that is an implementation issue in zinclabs integration

thanks
