### ISSUE TITLE
Google storage signature issue

### ISSUE THREAD

**Issue by alextur** [minio/minio-go#1800]
https://github.com/minio/minio-go/blob/5b159884739dd2c6330b423378de330775f3c93b/api.go#L158

All requsts to Google Storage lead to signature error:
`The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.`

As of September 2020, Google Cloud Storage only supports request signing using version 4 of the Signature Version.

**Comment by sprat** [comment]
I've double-checked today by modifying the override line in the `minio.New` method which forces a V2 signature for Google endpoints and it seems that both V2 and V4 signatures are working properly: I can perform a bucket listing in both cases. I would suggest removing the special case in the code since V4 signatures are better. But I must admit that I don't understand all the uses of the `overrideSignerType` field in the code, so I'm reluctant to file a pull request for that.
