### ISSUE TITLE
Unable to delete the folder inside the bucket.

### ISSUE THREAD

**Issue by ShowStopper3** [minio/minio-go#1914]
Hi All,

I have a folder structure like **Bucket/A/B/C/File.jpg**

Now when I use the API like below, it should delete the folder **A/B/C** along with file. However, the below code is printing done, but no folder deletion took place only the file **File.jpg** is being deleted.

```
    if mh.s3ClientV2 != nil {
		// Create a done channel to control 'ListObjects' go routine.
		objectsCh := make(chan string)

		// Indicate to our routine to exit cleanly upon return.
		defer close(objectsCh)
		opts := minio.ListObjectsOptions{
			UseV1:     false,
			Prefix:    "A",
			Recursive: true,
		}
		// List all objects from a bucket-name with a matching prefix.
		for object := range mh.s3ClientV2.ListObjects(context.Background(), "Bucket", opts) {
			if object.Err != nil {
				log.Println(object.Err)
			}
			log.Println("From list objects in delete ", object)
			fName := object.Key
			log.Println("Path", fName)
			errorCh := mh.s3ClientV2.RemoveObject(context.Background(), "Bucket", object.Key,
				minio.RemoveObjectOptions{ForceDelete: true, GovernanceBypass: true})
			if errorCh != nil {
				log.Printf("error", errorCh)

			} else {
				log.Println("done")
			}
		}

	}

```

**Comment by VerysignVL** [comment]
When you delete an object in S3, you're deleting an individual object (like Bucket/A/B/C/File.jpg). Deleting this object won't automatically delete the 'folders' (A/B/C) because they don't exist as distinct entities; they're just part of the object's key.

If you want to delete everything under Bucket/A/B/C/, you need to list all objects with the prefix A/B/C/ and delete each one. Your current code seems to be doing this, but it's only specifying A as the prefix, which might delete more than you intend if there are other objects starting with A that are not in A/B/C/.
