### ISSUE TITLE
minio-go: API change to presignedURL broke gitlab-ci

### ISSUE THREAD

**Issue by wpostma** [minio/minio-go#405]
If I understand Go's packaging system, the expectation is that you start a new repository name on github when you have unstable or API breaking changes.
(reference:http://stackoverflow.com/questions/24855081/how-do-i-import-a-specific-version-of-a-package)

This commit changes and breaks existing code that depends on the old API:
https://github.com/minio/minio-go/commit/9892e8f798ed44a6e54984b407059f8784865b97

Was this necessary and intentional? Unnecessary and unintentional? Some mixture?

Currently the gitlab-ci-multirunner module cache.go, and one assumes others, have code like this:

```

func getS3DownloadURL(build *common.Build, key string) (url string) {
	cache := build.Runner.Cache
	objectName := getCacheObjectName(build, cache, key)
	if objectName == "" {
		return
	}

	scl, err := getCacheStorageClient(cache)
	if err != nil {
		logrus.Warningln(err)
		return
	}

	url, err = scl.PresignedGetObject(cache.BucketName, objectName, time.Second*time.Duration(build.Timeout), nil)
	if err != nil {
		logrus.Warningln(err)
		return
	}
	return
}
```

Is it expected that this upstream dependency should discover this change by the CI breaking, and then figure out how to rewrite their code to use the new types?  Do I report this as a bug to the gitlab-ci team or do you consider this a bug in your minio-go library that you don't have a stable ABI?

**Comment by harshavardhana** [comment]
> Is it expected that this upstream dependency should discover this change by the CI breaking, and then figure out how to rewrite their code to use the new types? Do I report this as a bug to the gitlab-ci team or do you consider this a bug in your minio-go library that you don't have a stable ABI?

Apologies.  This is entirely our fault as we changed it.  

Usually in golang packages vendorize and stick to a particular version or commit if necessary using perhaps https://github.com/Masterminds/glide or any of the tools mentioned here https://github.com/golang/go/wiki/PackageManagementTools. 

On the other side API changes were needed to bring in some new functionalities and deprecate old ones for projects like https://restic.github.io/ and https://github.com/minio/mc 

We can work with the gitlab-ci team and help them vendorize dependencies in a cleaner way so that the issues like this do not occur. 

Will that be acceptable @wpostma ?

**Comment by harshavardhana** [comment]
Looks like - this has been updated on gitlab-ci-runner. 

```
commit fdb1bf1df49e9869c8479a1d3d29d8222d6a77ae
Author: Kamil Trzcinski <ayufan@ayufan.eu>
Date:   Sat May 14 11:03:32 2016 -0500

    Update mimio-go to a newest version
``` 

We will evaluate - http://labix.org/gopkg.in to maintain the versioning properly so that during a 'go get' things don't fail.

**Comment by wpostma** [comment]
The Upstream breakage I noticed is fixed for that one upstream user now.  Not sure how many other upstream go projects or libraries are affected so may want to leave this issue for comments (to avoid duplicates being logged).

Thanks for the quick discussion.   Not blaming anybody just trying to understand what's what, as I'm a brand new Go dev.

**Comment by harshavardhana** [comment]
> The Upstream breakage I noticed is fixed for that one upstream user now. Not sure how many other upstream go projects or libraries are affected so may want to leave this issue for comments (to avoid duplicates being logged).
> 
> Thanks for the quick discussion. Not blaming anybody just trying to understand what's what, as I'm a brand new Go dev.

One way to solve this is we move to http://labix.org/gopkg.in or something similar/custom domain. Another is upgrading to go1.5 and above version using the new "vendor" directory support which would mean that vendorized packages would never be referenced to "https://github.com/minio/minio-go" master instead they will be compiled from whatever the project vendorized commit for. 

I see that `gitlab-ci-multirunner` uses `Godeps` which doesn't automatically do this so if you did "go get gitlab.com/gitlab-org/gitlab-ci-multi-runner"  - then it would end up pulling sources from the master branch here unless URL itself had a way to distinguish which is hwat is http://labix.org/gopkg.in is for. 

Another convenient way is `gitlab.com/gitlab-org/gitlab-ci-multi-runner` also uses Makefile so if you happen to just 'git clone' the repo then a simple 'make' should suffice as well. 

We will see what fits best and make it simpler for applications to easily depend on this.

**Comment by harshavardhana** [comment]
Vendoring should be done based http://gopkg.in/minio/minio-go.v2 
 on this from now on, so that the applications vendorized using 'github.com' to master won't break and they stick to particular versions and update as they please.

Relevant patch has been submitted - https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/merge_requests/242 

Closing this issue.
