### ISSUE TITLE
Lack of location wording in the Golang API reference docs

### ISSUE THREAD

**Issue by justinclift** [minio/minio-go#534]
Just noticed something (not major), when attempting to use the Golang API `MakeBucket()` command for the first time.

The info and example given talks about AWS regions, but doesn't mention what should be done when not using AWS.  eg when creating buckets in a Minio server

At a guess (without investigation yet), it'll  probably default to something.  This issue is just to point out that the info about non-AWS use should be in the `MakeBucket()` docs. :smile:

**Comment by GarimaKapoor** [comment]
@koolhead17 check if we need to update our documentation with the suggestion.

**Comment by koolhead17** [comment]
@GarimaKapoor @harshavardhana suggestion would be to modify all the client library doc and mention that for AWS we support all the public listed endpoint and for minio by default us-east-1

Please advice and i will get it updated.

**Comment by krisis** [comment]
@justinclift, for non-AWS use, specifically for minio server, location defaults to `us-east-1`. So, minio-go SDK's default location just works. Further, minio server is capable of handling region names other than AWS regions and the SDKs work when used with the configured location.

Since everything "just works (TM)" with minio-go SDK and minio server, with ``us-east-1`` as the default region, we avoid digressing into specifics of non-default minio server configuration. This is why we don't have an explicit non-AWS description for available regions. Does this make sense?

**Comment by justinclift** [comment]
Yeah, my point is that this should be mentioned in the docs instead of the user having to wonder.

For command line utils (etc) things "magically just working" is cool :smile:, but documentation is for making sure people know how/why things work.  This is a one of those cases of letting people know what it's doing, so they don't need to worry about potential edge cases (etc).

**Comment by krisis** [comment]
@justinclift would it help if we added the following note?
"When used with minio server refer its config file for region information."

**Comment by justinclift** [comment]
Maybe "When used with minio server, use the region specified in it's config file (defaults to us-east-1)."
