### ISSUE TITLE
Multiple sources those use client side encryption in copy object api should return error.

### ISSUE THREAD

**Issue by balamurugana** [minio/minio-go#738]
Current [implementation](https://github.com/minio/minio-go/pull/715) continues destination object creation if client side encryption is used in multi source object input.  As the resultant object is not useful, copy object API should not allow this case and return error properly.

**Comment by donatello** [comment]
Since client-side encryption is well, _client side_, the possibility of the client being sophisticated enough to want to copy encrypted objects needs to be considered.

Consider the possibility of a client using this library but storing the encryption keys separately elsewhere. It will call put-object-with-client-encryption with encryption keys, and then want to concatenate them using ComposeAPI to create a kind of archive object. The client has all the info to even extract and decrypt files from the archive object. So why should compose-api stop the user from concatenating client side encrypted objects?

**Comment by donatello** [comment]
I just checked with some code that AWS S3 does not mess check these headers at all. We can copy client-side encrypted objects, concatenate them, etc and the server just does it. Code used to check: https://gist.github.com/donatello/bbdefac623bc258f1000b318c6d9c120

It seems clear to me that the library should not unnecessarily interpret these headers.
